/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const MountType = t.enumtype({
  "Flush": "flush",
  "Matted": "matted",
  "Float": "float",
});

const exportedTypeSuite: t.ITypeSuite = {
  MountType,
};
export default exportedTypeSuite;
