/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const WorksheetRecord = t.iface([], {
  "id": t.opt("number"),
  "label": "string",
  "modified": "number",
  "data": "WorksheetData",
});

const exportedTypeSuite: t.ITypeSuite = {
  WorksheetRecord,
};
export default exportedTypeSuite;
