/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const WorksheetData = t.iface([], {
  "title": "string",
  "artist": "string",
  "mountType": "MountType",
  "width": "string",
  "revealLeft": "string",
  "revealRight": "string",
  "height": "string",
  "revealTop": "string",
  "revealBottom": "string",
  "frameWidth": "string",
  "frameDepth": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  WorksheetData,
};
export default exportedTypeSuite;
